###################
# Gnüwhine recipe #
###################

# Make your own Gnüwhine
# Choose from the following ingredients: krambambuli, rum, cognac, sugar, cinnamon, coffee, lemon, laxatives
# the key is the ingredient, the value is the amount in milliliter or percentage. Example:
# krabambuli: 70%
# or
# rum: 10ml

# Make a fork from https://github.com/hsbxl/gnuwhine and your fork will be listed on our interface.
# For making multiple variants, use branches.
#
# Happy Gnüwhining!


krambambuli: 60%
rum: 20%
lemon: 5%
sugar: 5%
laxatives: 10%
